os:
  - linux

language: node_js

services:
  - docker

install: npm ci

addons:
  sonarcloud:
    organization: "open-cluster-management"
    token:
      secure: "gBTBmqMJwT10RClA75I8fKHun+05Ja4MYu1yDegRSg/7GCS+SGQHSLX6AaDiiP/zgaX0ffXACMS/RiLTs8pQauQQUEy5bTwUIxbkHHYZlSMQDtmuaQerRVsI5017zqrfd56c2qMvRFg+7ekd72pl8qgRI8CJaMaa27lnKxlagBgthXANwcJqKxqYfuJStIF23hzOagOonh1FNsO7kqNWErEJGNvi99mA4GVMfnllZliZeXWILn7tdjgvKZiwz7UoGHYSqJkchW7RSNaJe0IDjMyDKzKpn5DMTE48VsjY+qZbaar3TvKMkjoUmnPRGe/1eJU2MA29v3EEJ/bCG15b3lZ2v/ZMiN5jMsGorCzAeokLc7TQ+/ssyVC1UwwlGdpb7kM8QjYyD+pgEXWurJozdVzUw6TrpSEXWBzAjaF+R4D6/9dtyb2Bn1QzDgukPr0+U0iLj/23+3MklfD0wLcC7Hd5YDYxAihbdkEujXWTryvgzj8hOmUUjynAdBT5J49earzVvhJTPSZWpyPfqFPJAi1c5OzTSJgvUEeqxUYswIX1qDWddNYVSvtr6mQmwTj4GKuC2rOWUvgN8Vp2vtLPCBl5UZBIeFuN+L/+DgqGewudkFognKPg2DCuBlKrogZHwo1MyK4kj5VCH4QkpVZAtzVuMcsnjDPeaAO0oV5vTdc="

env:
  global:
    # Required
    - OS=linux
    - COMPONENT_TAG_EXTENSION="-${TRAVIS_COMMIT}"

    # Component Specific
    - COMPONENT_INIT_COMMAND=${TRAVIS_BUILD_DIR}/install-dependencies.sh
    - COMPONENT_BUILD_COMMAND=${TRAVIS_BUILD_DIR}/build.sh
    - COMPONENT_UNIT_TEST_COMMAND=${TRAVIS_BUILD_DIR}/unit-test.sh
    - COMPONENT_E2E_TEST_COMMAND=${TRAVIS_BUILD_DIR}/e2e-test.sh

branches:
  only:
    - main
    - /^release-[0-9]+\..*$/

stages:
  - build
  - test
  - publish

jobs:
  include:
    - stage: build
      name: "Build the test image and push it"
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - make
        - make component/build
        - make component/push
        - if [ "$IMAGE_SCAN" != "false" ]; then make security/scans; fi;
        - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "main" ]; then
          export COMPONENT_NEWTAG="latest";
          make component/tag;
          export COMPONENT_VERSION="latest";
          export COMPONENT_TAG_EXTENSION="";
          make component/push;
          fi;
    - stage: test
      name: "Run unit tests"
      script:
        # Set the image tag differently for PRs
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        # Bootstrap the build harness, pull test image, and run unit tests.
        - make
        - make component/pull
        - make sonar/js/jest-init
        - make component/test/unit
        - make sonar/js
    - stage: test
      name: "Deploy the image to a cluster and run e2e tests"
      if: type = pull_request
      script:
        #Check out a clusterpool, set up oc, deploy, run e2e tests, and return clusterpool cluster
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - make
        - make component/pull
        - make component/test/e2e
    - stage: release-ff
      name: "Push commits to current release branch"
      if: type = push AND branch =~ /^main$/
      script:
        - make
        - make release-ff
    - stage: publish
      name: "Publish the image to quay with an official version/sha tag and publish entry to integration pipeline stage"
      if: type = push AND branch =~ /^release-[0-9]+\..*$/
      script:
        - make
        - make pipeline-manifest/update PIPELINE_MANIFEST_COMPONENT_SHA256=${TRAVIS_COMMIT} PIPELINE_MANIFEST_COMPONENT_REPO=${TRAVIS_REPO_SLUG} PIPELINE_MANIFEST_BRANCH=${TRAVIS_BRANCH}
